# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"du": "00_psql.ipynb",
         "query": "00_psql.ipynb",
         "current": "00_psql.ipynb",
         "kill": "00_tools.ipynb",
         "schema": "00_psql.ipynb",
         "LocalBase": "00_psql.ipynb",
         "insert_on_conflict": "00_psql.ipynb",
         "read_sql": "00_psql.ipynb",
         "series2tensor": "00_tools.ipynb",
         "get_image_from_url": "00_tools.ipynb",
         "get_hash_folder": "00_tools.ipynb",
         "save_selected_cities": "00_tools.ipynb",
         "save_location_dicts": "00_tools.ipynb",
         "get_top_n_countries": "00_tools.ipynb",
         "path_info": "00_tools.ipynb",
         "rm_r": "00_tools.ipynb",
         "search_notebooks": "00_tools.ipynb",
         "df_chunk_generator": "00_tools.ipynb",
         "Path.ls": "00_tools.ipynb",
         "docker_container": "00_tools.ipynb",
         "LogDBHandler": "00_tools.ipynb",
         "get_logger": "00_tools.ipynb",
         "read_image_from_url": "00_tools.ipynb",
         "compound_return": "00_tools.ipynb",
         "copy_func": "00_tools.ipynb",
         "patch_to": "00_tools.ipynb",
         "patch": "00_tools.ipynb",
         "to_pickle": "00_tools.ipynb",
         "from_pickle": "00_tools.ipynb",
         "telegram": "00_tools.ipynb",
         "pdrows": "00_tools.ipynb",
         "pd_highlight": "00_tools.ipynb",
         "inline": "00_tools.ipynb",
         "plot_map": "00_tools.ipynb",
         "htop": "00_tools.ipynb",
         "get_proxies": "00_tools.ipynb",
         "append_csv": "00_tools.ipynb",
         "repeat_df": "00_tools.ipynb",
         "to_sql": "00_tools.ipynb",
         "timestamp2int": "00_tools.ipynb",
         "pd_timestamp": "00_tools.ipynb",
         "startEndTimestamp": "00_tools.ipynb",
         "pd_set_float": "00_tools.ipynb",
         "plot_multiple_y": "00_tools.ipynb",
         "sql_head": "00_tools.ipynb",
         "make_clickable": "00_tools.ipynb"}

modules = ["psql.py",
           "tools.py"]

doc_url = "https://{user}.github.io/mytools/"

git_url = "https://github.com/{user}/mytools/tree/{branch}/"

def custom_doc_links(name): return None
