# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_custom_pandas.ipynb.

# %% auto 0
__all__ = ['read_sql_query']

# %% ../00_custom_pandas.ipynb 1
from pandas.io.sql import  _convert_params, _wrap_result

def read_sql_query(query, engine, chunksize, index_col=None, coerce_float=True, params=None, parse_dates=None,):
    args = _convert_params(query, params)        
    with engine.connect() as conn:
        result = conn.execution_options(stream_results=True).execute(*args)
        columns = result.keys()
        for partition in result.partitions(chunksize):
            yield _wrap_result(partition,
                               columns,
                               index_col=index_col,
                               coerce_float=coerce_float,
                               parse_dates=parse_dates,)
