# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_paths.ipynb.

# %% auto 0
__all__ = ['main_path', 'data_path', 'ssd_path', 'api_path', 'datasets_path']

# %% ../00_paths.ipynb 1
from pathlib import Path
import os

# %% ../00_paths.ipynb 2
main_path = Path(os.getenv("HOME"))
data_path = main_path/'data'
ssd_path = main_path/'ssd'
api_path = data_path/'api'
datasets_path = data_path/'datasets'
